export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const BUCKETLISTS_REQUEST = "BUCKETLISTS_REQUEST";
export const BUCKETLISTS_FETCHED = "BUCKETLIST_FETCHED";
export const BUCKETLISTS_FETCH_FAILED = "BUCKETLISTS_FETCH_FAILED";

export const CURRENT_USER_REQUEST = "CURRENT_USER_REQUEST";
export const CURRENT_USER_FETCHED = "CURRENT_USER_FETCHED";
export const CURRENT_USER_FETCHED_FAILED = "CURRENT_USER_FETCHED_FAILED";
export const CURRENT_USER_EDIT_REQUEST = "CURRENT_USER_EDIT_REQUEST";
export const CURRENT_USER_EDIT_CLOSE = "CURRENT_USER_EDIT_CLOSE";
export const CURRENT_USER_UPDATE_REQUEST = "CURRENT_USER_UPDATE_REQUEST";
export const CURRENT_USER_UPDATE = "CURRENT_USER_UPDATE";
export const CURRENT_USER_UPDATE_FAILED = "CURRENT_USER_UPDATE_FAILED";