export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const BUCKETLISTS_REQUEST = "BUCKETLISTS_REQUEST";
export const BUCKETLISTS_FETCHED = "BUCKETLIST_FETCHED";
export const BUCKETLISTS_FETCH_FAILED = "BUCKETLISTS_FETCH_FAILED";
export const BUCKETLISTS_CREATE_REQUEST = "BUCKETLISTS_CREATE_REQUEST";
export const BUCKETLISTS_NEW_REQUEST = "BUCKETLISTS_NEW_REQUEST";
export const BUCKETLISTS_CREATE_CLOSE = "BUCKETLISTS_CREATE_CLOSE";
export const BUCKETLISTS_CREATED = "BUCKETLISTS_CREATED";
export const BUCKETLISTS_CREATE_FAILED = "BUCKETLISTS_CREATE_FAILED";
export const BUCKETLISTS_UPDATE_REQUEST = "BUCKETLISTS_UPDATE_REQUEST";
export const BUCKETLISTS_UPDATED = "BUCKETLISTS_UPDATED";
export const BUCKETLISTS_UPDATE_FAILED = "BUCKETLISTS_UPDATE_FAILED";
export const BUCKETLISTS_UPDATE_CLOSE = "BUCKETLISTS_UPDATE_CLOSE";
export const BUCKETLISTS_DELETE_REQUEST = "BUCKETLISTS_DELETE_REQUEST";
export const BUCKETLISTS_DELETE_CLOSE = "BUCKETLISTS_DELETE_CLOSE";
export const BUCKETLISTS_DELETED = "BUCKETLISTS_DELETED";
export const BUCKETLISTS_DELETE_FAILED = "BUCKETLISTS_DELETE_FAILED";

export const ITEMS_REQUEST = "ITEMS_REQUEST";

export const CURRENT_USER_REQUEST = "CURRENT_USER_REQUEST";
export const CURRENT_USER_FETCHED = "CURRENT_USER_FETCHED";
export const CURRENT_USER_FETCHED_FAILED = "CURRENT_USER_FETCHED_FAILED";
export const CURRENT_USER_EDIT_REQUEST = "CURRENT_USER_EDIT_REQUEST";
export const CURRENT_USER_EDIT_CLOSE = "CURRENT_USER_EDIT_CLOSE";
export const CURRENT_USER_UPDATE_REQUEST = "CURRENT_USER_UPDATE_REQUEST";
export const CURRENT_USER_UPDATE_FAILED = "CURRENT_USER_UPDATE_FAILED";